### INFORMATIONS ###

# Repository : https://github.com/matthieu-locussol/golPlayground
# Builds     : https://travis-ci.com/matthieu-locussol/golPlayground

language:
    cpp

matrix:
    include:
        - env:
            - BUILD_TYPE=Release
          os: osx
          osx_image: xcode11
        - env:
            - BUILD_TYPE=Release
          os: osx
          osx_image: xcode10
        - env:
            - BUILD_TYPE=Release
          os: osx
          osx_image: xcode9
        - env:
            - BUILD_TYPE=Release
          os: osx
          osx_image: xcode8
        - env:
            - BUILD_TYPE=Release
          os: osx
          osx_image: xcode7.3
        - env:
            - BUILD_TYPE=Release
          os: osx
          osx_image: xcode6.4

install:
    - mv Build/install_osx.sh .
    - sudo ./install_osx.sh
    - cd Build # golPlayground/Build
    - sudo mkdir -p Application/Binaries/
    - sudo mv Application/golPlayground Application/Binaries/.
    - sudo mv Application golPlayground
    - sudo zip -r golPlayground:${TRAVIS_OS_NAME}-${TRAVIS_OSX_IMAGE}.zip golPlayground

script:
    - ./Tests/golTests
    - echo ${SSH_PRIVATE_KEY} | tr -d '\r' | ssh-add - > /dev/null
    - sudo mkdir -p ~/.ssh
    - sudo chmod 700 ~/.ssh
    - sudo scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./Build/golPlayground*.zip ${USERNAME}@${HOST}:./golPlayground_Releases/latest/osx/.